### ISSUE TITLE
Use the Releases function of Github instead of Mega

### ISSUE THREAD

**Issue by sigboe** [betavr/steamvr_driver_hydra#1]
I suggest that you use the [Releases](https://github.com/betavr/steamvr_driver_hydra/releases) function of Github instead of linking to Mega. It supports both change logs and multiple files.

**Comment by betavr** [comment]
Yeah, looks much better than mega. I'm going to put it under Releases starting from the next build, which will also have a normal windows installer too.

**Comment by sigboe** [comment]
Remember to detect the steam installation directory, mine is at
D:\Programs\Steam

:-)

**Comment by betavr** [comment]
new release added with auto detection of steam folder.
