### ISSUE TITLE
SteamVR not seeing Hydras at all.

### ISSUE THREAD

**Issue by OverlordMIke** [betavr/steamvr_driver_hydra#12]
Followed all instructions given. Controller icons stay grey, SteamVR just won't acknowledge the existence of my Hydra. Tried uninstalling Steam from it's D: installation and reinstalling it in C:, still no luck. Tell me what you need and where it is, I'll provide.

**Comment by betavr** [comment]
Try to copy the hydra folder from the driver install to the ...\SteamVR\drivers directory.

**Comment by OverlordMIke** [comment]
I've tried that, still nothing. I also do have ""activateMultipleDrivers" : true,"

**Comment by betavr** [comment]
That's weird. We're going to need the contents of your vrserver.txt (found in steam\logs), and also the output of vrpathreg.exe (in steamvr\bin) to further analyze the problem.

**Comment by OverlordMIke** [comment]
There doesn't seem to be a vrserver.txt in the logs folder, and vrpathreg.exe just flashes a prompt window up and goes away instantly.

**Comment by OverlordMIke** [comment]
I just started SteamVR and it said they were connected but not tracking motion. So I quit out and got my Rift DK2 on and ready, started SteamVR again, and they weren't connected again. Can't seem to reproduce what I just got...

EDIT
Okay. Only if my DK2 is turned off. I can unplug the USB for the Hydra and plug it back in, start SteamVR and it will say they are connected but not tracking. If the DK2 is turned on, nothing will let the Hydra connect. No matter what, when I end SteamVR, Windows throws an error at me "VR Server has stopped working."

**Comment by OverlordMIke** [comment]
I've figured it out, and it's odd. Turns out that the logs and steamvr config are still being read from the location on D:\, so I placed everything in there and it is working fine. It's completely ignoring the files and folders on C:\ and defaulting the D:.

**Comment by cbuchner1** [comment]
NOTE: the log and config paths can be adjusted using the vrpathreg tool as
well.

2016-05-17 10:51 GMT+02:00 OverlordMIke notifications@github.com:

**Comment by betavr** [comment]
@OverlordMIke I'm glad you worked it out. Vrpathreg.exe is a command line tool, so you need to open a command line and try to run it from there. As @cbuchner1 pointed out the configuration values (log directory, etc) can only be altered by this tool.
