### ISSUE TITLE
Missing "Hold the thumbpad" mapping

### ISSUE THREAD

**Issue by koganei** [betavr/steamvr_driver_hydra#15]
Hi, I started playing The Gallery using this, and the first thing the game wants me to do is "hold the left thumbpad" which I seem unable to do with the Hydras. Any way to map this to the wand?

**Comment by betavr** [comment]
So the game needs you to place your thumb on the center of the touchpad without pressing it?

**Comment by koganei** [comment]
Yeah, exactly.

**Comment by nintenjo** [comment]
Another issue related to this is some SteamVR games require you to simply place your thumb on the tracker (like a touch pad) while others require you to actually depress the tracker like a button.. Doing this on an analogue stick is very clunky :( 

(I know this is more related to the way the game input options have been written, but is a frustration. A good example is Windlands that requires you to click an hold the analogue sticks to move / jump making it virtually unplayable.

One solution would be to assign a hydra button button to toggle the analogue sticks input from movement to a click when you push over a threshold? (with a small deadzone in the centre?)

**Comment by bobjwatts** [comment]
Would love to see a solution, The Gallery has this issue.

**Comment by betavr** [comment]
The feature has been Implemented in the latest release: https://github.com/betavr/steamvr_driver_hydra/releases/tag/v1.0.1.12

**Comment by bobjwatts** [comment]
Thanks betavr. I can see the the thumbpad dot lights up when I press '3' but I'm not sure it's really 'hold the thumbpad' rather it's 'touch the thumbpad'. In Call of the Starseed you have to 'press' the thumbpad to use blink, when I press '3' it doesn't register. Sorry I don't have a Vive to test.

**Comment by betavr** [comment]
Unfortunately I don't have that game, so I can't test it either. Have you tried pressing button 3 and the joystick button at the same time?

**Comment by bobjwatts** [comment]
I just gave it another go, trying everything I could, no luck.

**Comment by AlexLogin0ff** [comment]
In Call of the Starseed is not working thumbpad :(

**Comment by forrestv** [comment]
I can confirm that this still isn't working. Here's a screenshot of the prompt in the game:

<img src="http://u.forre.st/u/fyozjoch/blink.PNG"/>

@betavr, any idea what could be missing? I can try things (recompiling, etc), but it looks like the driver is doing all it can... What could Starseed be looking at besides the `k_EButton_Axis0` bit in `ulButtonTouched`/`ulButtonPressed`?

**Comment by forrestv** [comment]
Hypotheses I have:
- The k_EButton_Button3 pressed/touched events somehow result in Starseed ignoring the k_EButton_Axis0 touch event
- Starseed needs TouchPadMove events, which could possibly be injected via the VendorSpecificEvent callback

**Comment by betavr** [comment]
Thanks for the investigation. Will upload a new version soon without the Button3 keypress event.

Btw does the reticle appear in the game (step 2. on the picture)?

**Comment by betavr** [comment]
the fix is up: https://github.com/betavr/steamvr_driver_hydra/releases/tag/v1.0.1.13

**Comment by forrestv** [comment]
Thanks! I just tried it, but it didn't fix it.

No, the reticle does not appear.

So, this still leaves the second hypothesis. I'm installing VS 2015 right now to try to implement it.

**Comment by betavr** [comment]
Another quick fix: the joystick axis is now reported as zero when the deadzone is active, please try it: https://github.com/betavr/steamvr_driver_hydra/releases/tag/v1.0.1.14

Looking forward to what you find with touchpadmove!

**Comment by forrestv** [comment]
That didn't help either. :/

**Comment by betavr** [comment]
Nvm, I contacted the developers. Will report back when they respond.

**Comment by chedigitalproduction** [comment]
The developers have stated that they won't support Hydra, even though it was a stretch goal in the Kickstarter. Hopefully they do respond though, looks like we are getting closer to understanding the issue.

**Comment by betavr** [comment]
Yeah, received a negative response. To sum it up, they are satisfied with the current situation. They don't want Oculus users to play the game until it has been officially launched for the Oculus platform: http://steamcommunity.com/app/270130/discussions/0/351660338732546659/

They are concerned that ppl aren't going to have the "proper experience".

**Comment by betavr** [comment]
Ok, I just added a new section in the wiki: https://github.com/betavr/steamvr_driver_hydra/wiki#list-of-unsupported-games

I think this case is closed.

**Comment by bobjwatts** [comment]
Sad face. Thanks for trying betavr.

**Comment by betavr** [comment]
Yeah kinda disappointing. Oculus is trying hard to build a fence around it's garden, and I wouldn't be too surprised to find out that they have an agreement with the Cloudhead guys.

**Comment by forrestv** [comment]
It appears that this problem isn't fixable from within steamvr_driver_hydra. It's a result of directly checking whether the _HMD_ is a Vive.

On the bright side, you can work around this by pressing W to blink and using the mouse's scroll wheel to rotate the play area, although that isn't fun at all. Thanks, Cloudhead.

**Comment by AlexLogin0ff** [comment]
this function can be specifically applied to the new individual driver for this game or add this feature in Motioncreator 2,  it is to work together??

**Comment by betavr** [comment]
@forrestv So you're saying it is possible to blink using the keyboard and mouse? This is interesting, can you please elaborate?

@AlexLogin0ff Driver features can be enabled/disabled in the steamvr.vrsettings file, so there is no need for an individual driver.

**Comment by nintenjo** [comment]
Is this not the same issue i reported above? I feel like its a separate issue now :) (in which case i should open another thread).

I had issue with the main SteamVR gallery and games that require you to click the touchpad directions as if it were a digital D-Pad.. this on the Hydra analog stick is very difficult to do as you have to push the direction and then click the stick in.. (simple in theory) but games like Windlands require you to use this method to navigate in first person.. I was looking for a solution that allowed users to toggle the function of the analog stick from default (as it is now) to a digital mode so any direction pressed on the stick also triggers a 'on-click' event on the touchpad? (perhaps button 4 toggles modes?)

This issue will also affect a lot of games that support the Oculus Move controllers which have the same analog sticks as the Hydra.

**Comment by betavr** [comment]
@nintenjo yeah, please open a separate issue for that one, thanks!
