### ISSUE TITLE
Controllers doesn't work with some games.

### ISSUE THREAD

**Issue by rafgim** [betavr/steamvr_driver_hydra#16]
When i start some games (poolnationvr or ligthblade vr), the controllers doesn't work. It only works the buttons but not the movement and there is only one controller on the floor and i can't move anything. With steamvr or other games it works perfectly. Thanks.

**Comment by betavr** [comment]
Yeah, Unreal Engine games currently has problems. Unfortunately this can't be fixed from the driver side - you are going to have to ask the developer to fix it.

**Comment by rafgim** [comment]
Ok, thanks.
