### ISSUE TITLE
Hydra not working in Steam VR with latest build?

### ISSUE THREAD

**Issue by vonkoda** [betavr/steamvr_driver_hydra#19]
Steam VR ver 1466127800 (Jun 17)?  At first Steam VR was freezing at start up. I disconnected the Hydra and it starts now but doesnt detect the Hydra's any longer.

I opted into the older (I presume?) v1464744840 Steam VR  beta and they are working again. Confirmed!

EDIT: Looks like its already fixed with driver release!
https://github.com/betavr/steamvr_driver_hydra/releases/tag/v1.0.1.10

**Comment by betavr** [comment]
Yes, this problem was resolved yesterday.
