### ISSUE TITLE
Trouble building project

### ISSUE THREAD

**Issue by Bletotum** [betavr/steamvr_driver_hydra#23]
http://i.imgur.com/onLtxp2.png

I've linked the appropriate old version of OpenVR as instructed, as well as the steam-installed sixense SDK. I don't know what I'm supposed to do with this error, though, to try modding this.

This is on VS Community 2013.

**Comment by betavr** [comment]
Yeah, you need to build it with the latest OpenVR sdk, and keep in mind the project is for VS2015 not 13.

Also make sure to download the sixense sdk from sixense, not from steam like the readme says! (http://sixense.com/windowssdkdownload) The steam version only has dlls for VS2010.

**Comment by Bletotum** [comment]
I just tried it the way you said, with the latest OpenVR and the proper sixense under VS2015. I've still got the same error. Is there something I forgot?

**Comment by betavr** [comment]
Ok, after taking a closer look at your pic, it says it's missing some overrides. So you probably have an old revision of the driver source.

**Comment by Bletotum** [comment]
It's your current version of this fork with the other up to date sources.

**Comment by betavr** [comment]
Check your copy of driver_hydra.h, and make sure you can see these lines:

`virtual vr::ITrackedDeviceServerDriver * GetTrackedDeviceDriver( uint32_t unWhich ) override;`
`virtual vr::ITrackedDeviceServerDriver * FindTrackedDeviceDriver(const char * pchId) override;`

**Comment by Bletotum** [comment]
Both of those lines are there. Later, in the same file, this: http://i.imgur.com/l5EQlqM.png

**Comment by betavr** [comment]
I just checked and Openvr has been updated to 1.0.2, but the driver uses 1.0.0. It is possible this is the cause of your problem. Try to check out release 1.0.0 of openvr: https://github.com/ValveSoftware/openvr/releases/tag/v1.0.0

**Comment by Bletotum** [comment]
That did the trick; thanks!

**Comment by betavr** [comment]
Well, I guess it's time for an openvr upgrade once again. Good to know it worked out for you!

**Comment by betavr** [comment]
updated to OpenVR 1.0.2: https://github.com/betavr/steamvr_driver_hydra/commit/52f25c5dca261c8eea96f518e9f24f0fcb49f6ac
