### ISSUE TITLE
Razer Hydra not detected in some games (SteamVR)

### ISSUE THREAD

**Issue by AlexLogin0ff** [betavr/steamvr_driver_hydra#25]
Razer Hydra not detected in games (UE4) - NVIDIA® VR Funhouse, The Nest, Out of Ammo, Lightblade VR... :(

**Comment by SooSiaal** [comment]
You can add raw data to the list,it detects controllers but not working right at all

**Comment by betavr** [comment]
Thanks, they will be added to the unsupported list. 

Can you tell me in more detail why these games don't work?

**Comment by betavr** [comment]
Also, can you please verify the method described in the post below works?
https://www.reddit.com/r/oculus/comments/4svgi0/nvidia_vr_funhouse_with_leap_motion/

**Comment by SooSiaal** [comment]
for Raw Data,turning compatibility on or off doesnt change a thing, it sort of recognizes the controllers,but the hands ingame dont move along with the hydras (rotation does work somewhat),left trigger activates right trigger as well,those sort of things

**Comment by AlexLogin0ff** [comment]
Do not work at the program level, you need to look  in NVIDIA® VR Funhouse, free to Steam - http://store.steampowered.com/app/468700/

**Comment by betavr** [comment]
@SooSiaal ok, thanks!

@AlexLogin0ff I'd try it myself, but I can't launch it on my AMD gpu.

**Comment by AlexLogin0ff** [comment]
the problem is solved, it will be interesting to all -
Rift + Hydras (compatibility mode for win 7 on VRFunhouse.exe) it works flawless and other games on UE4 !!!
Remains an open question with "Raw Data", controllers at the start of the game is not in his place and they can not be calibrated

**Comment by rblostwolf** [comment]
not detecting them in fruit ninja vr

**Comment by rblostwolf** [comment]
oh sorry just saw the compatibility thing you mentioned and it works now thanks for that

**Comment by AlexLogin0ff** [comment]
tested -  NVIDIA® VR Funhouse, Гнездо, патроны, The Path of Greatest Resistance

**Comment by AlexLogin0ff** [comment]
Tested! - NVIDIA® VR Funhouse, The Nest, Out of Ammo, PoolNation VR, The Path of Greatest Resistance,  Portal Stories: VR, The Solus Project

**Comment by betavr** [comment]
Awesome news! :+1: Method added to the wiki, thank you everyone for testing!

Regarding Raw Data, I'll try to speak with the developer.

**Comment by SooSiaal** [comment]
I asked them a qustion about it on facebook,think it got misunderstood as they said Hydra won't be supported :p
But as this driver emulates the vive wands i'm sure there are some possibilities getting it to work.. i'm no programmer so i can't be of much help there unfortunately

**Comment by AlexLogin0ff** [comment]
it is possible that in this subject will tell you to fix driver - https://www.reddit.com/r/Vive/comments/4syoio/psa_ue4_assigns_the_first_controller_you_turn_on/?st=iqo7j0po&sh=1b3002c1

**Comment by betavr** [comment]
Interesting, some ppl on reddit are saying that they can play Raw Data with the hydras:
https://www.reddit.com/r/oculus/comments/4sy8dv/raw_data_doesnt_work_with_rift_touch/d5df46h

**Comment by AlexLogin0ff** [comment]
You can play the Raw Data, if you put a Hydra base at shoulder level in front of you.
it is playable, but not perfect! 
Something interferes for the emulator in the game at the program level

**Comment by betavr** [comment]
Weird, so it basically ignores the calibration of the base station?

**Comment by AlexLogin0ff** [comment]
In Raw Data the controllers by themselves (they can not be calibrated), emulator only gives their inclusion in the game

**Comment by SooSiaal** [comment]
That is odd,will test this

**Comment by betavr** [comment]
@AlexLogin0ff maybe the game has built-in Hydra support, but it's broken. Can you try what happens if you press the system button (does the SteamVR dashboard appear)? Are the controllers still uncalibrated on the dashboard too?

**Comment by AlexLogin0ff** [comment]
if you click on SteamVR menu, you can see emulated controllers, they are here in perfect location, located in the game one's own way

**Comment by betavr** [comment]
Very strange, I can only assume it's accessing the hydra directly. Could you check if the game's install folder contains the file sixense.dll, or sixense_x64.dll?

**Comment by AlexLogin0ff** [comment]
![default](https://cloud.githubusercontent.com/assets/20149776/16901936/2e2e387a-4c62-11e6-9ca7-edee1374898a.jpg)

**Comment by AlexLogin0ff** [comment]
![default](https://cloud.githubusercontent.com/assets/20149776/16901951/7f1321f6-4c62-11e6-9c20-bf8ab79d80bc.jpg)

**Comment by betavr** [comment]
Wow, so they do have their own controller implementations. I'd try to remove the Sixense and SixenseStem folders, and see what happens in the game.

**Comment by AlexLogin0ff** [comment]
I tried, did not help

**Comment by betavr** [comment]
Delete all of the sixense_*.dll files from the game's folder, and make sure Steam doesn't reinstall them when you launch the game. Doing this should disable their built-in hydra driver.

**Comment by AlexLogin0ff** [comment]
version in game - OpenVR v0_9_12 
It has a value or not?

**Comment by AlexLogin0ff** [comment]
Я буду стараться, я напишу позже

**Comment by AlexLogin0ff** [comment]
unfortunately it did not help (

**Comment by AlexLogin0ff** [comment]
may need to change in this file -
![default](https://cloud.githubusercontent.com/assets/20149776/16902277/ecc5a5d0-4c6b-11e6-9d5d-19ab62ee87fc.png)

**Comment by AlexLogin0ff** [comment]
[/Script/Survios.SVRLocalPlayerSettings]
SyncedPlayerSettings=(ControllerMode=Motion,HMDMode=HMD,HMDType=Survios,HandTrackerParent=Head,HandTrackerBaseOrientation=(RelativeLocation=(X=66.143242,Y=-5.098728,Z=48.728882),RelativeRotator=(Pitch=77.475006,Yaw=-8.435512,Roll=-5.044755)),AvatarCollisionMode=IgnoreBodyAndInteractionCollisions)
MotionControllerSettings=(MotionControllerThumbPadMode=Analogue,MovementDeadZone=0.100000,ThumbPadMaxVal=0.800000,InitialMovementDelayZone=0.800000,InitialMovementDelayMaxDuration=0.200000,InitialMovementDelayMaxThumbMovementDistance=0.300000,bNormalizeThumbPadInput=False,bSetInitialTouchLocationAsJoystickOrigin=False,bInitialMovementDelayIsEnabled=True,bRequiresThumbstickClickForMovement=True)
FirstPersonAvatarMode=ArmsOnly

**Comment by betavr** [comment]
Can you provide more detail on why it didn't help? Did the game detect the hydra without the sixense dlls?

I'm trying to figure out if we can disable their Hydra driver completely, otherwise you are relying on their implementation, and I'm not sure I can help you with that. Although that SVRLocalPlayerSettings does look like it contains some kind of calibration data.

**Comment by SooSiaal** [comment]
yes it detects the controllers without the dlls but they still function the same as before,before pushing any button or trigger the wands ingame follow the hydras,but as soon as a button is pressed the ingame wand moves off to a random position (usually infront or above you) and is turned 180 degrees

**Comment by betavr** [comment]
Strange. Can you check if the Thirdparty\OpenVR directory contains a driver subdirectory?

**Comment by SooSiaal** [comment]
only the OpenVRv0_9_12 folder with the api dll

**Comment by frictionjones** [comment]
Hello, I just realized that the right mouse button does the same thing the right hydra trigger _should_ do in raw data; is it possible to map the right mouse button to that trigger?

**Comment by AlexLogin0ff** [comment]
Here in the video is the answer to your question - https://www.youtube.com/watch?v=p8ghvNIzWiw

**Comment by betavr** [comment]
Nice video! It looks like hemisphere tracking is not being enabled by the game's builting driver.

**Comment by SooSiaal** [comment]
I just tried putting hydra base at shoulder height but still no dice,same problem keeps happening :(

**Comment by betavr** [comment]
@SooSiaal Have you tried to disable/uninstall the hydra driver before starting raw data?

Btw the steam app will be online very soon, so the install/uninstall procedure will be much faster.

**Comment by SooSiaal** [comment]
ohh no i havent tried that yet hehe

**Comment by frictionjones** [comment]
Which hydra driver should be disabled or uninstalled?

**Comment by AlexLogin0ff** [comment]
drivers do not need to be removed

**Comment by AlexLogin0ff** [comment]
You need to correctly place the Hydra base at shoulder level, in the center of the area!!!! Themselves to be behind this area 
![1](https://cloud.githubusercontent.com/assets/20149776/17038874/ca7832a0-4fa8-11e6-9092-71b932be2072.png)

**Comment by betavr** [comment]
@frictionjones This driver, but @AlexLogin0ff just clarified that Raw Data works for him without removing it.

**Comment by betavr** [comment]
@AlexLogin0ff so the base station should be placed where the playarea center is?

**Comment by AlexLogin0ff** [comment]
Yes!!!

**Comment by betavr** [comment]
Awesome, can you guys please verify this? 

Also, is anyone here interested in betatesting the driver on Steam?

**Comment by AlexLogin0ff** [comment]
Of course!

**Comment by SooSiaal** [comment]
Sure thing,and it is somewhat working now,atleast much better than it was,gonna need a little finetuning with centering I guess,but this is promising atleast :)

**Comment by betavr** [comment]
Thanks guys, I really appreciate your help! Please write to hydradriver@betavr.com to receive your beta key.

**Comment by frictionjones** [comment]
Can you give step by step on how you got it working?

**Comment by rblostwolf** [comment]
once calibrated does the hydra base station need to remain at shoulder height?

**Comment by Honestydeceit** [comment]
Sorry, this just isn't working. Putting the base in the center of the room does nothing and putting the controllers next to the base does nothing, they just sit there and when picking the controllers back up, the hands are still fucked up. Honestly, it's completely unclear in the video just what this guy did to get it working, and I have no idea how to even start.

**Comment by rblostwolf** [comment]
he did the room calibration and when the steam thing asks for you to hold your head set in the centre of the room he also put the razer base station at shoulder height in the centre of the space. i'm not sure whether leaving it there at shoulder height is required after calibration  if it is i'm not going to do it as it would get in the way

**Comment by AlexLogin0ff** [comment]
Hydra station is put in the playarea center after installation Room SetUP! Before playing in Raw Data

**Comment by frictionjones** [comment]
Yes, I calibrated with the base station in the center of the space (at shoulder height), and it still doesn't work. Pressing either of the triggers sends the hands into the air, and putting the controllers on the base station and picking them up again changes nothing.

**Comment by AlexLogin0ff** [comment]
Further necessary to adjust the calibration in the game!

**Comment by frictionjones** [comment]
When you say "adjust the calibration," you're talking about putting the controllers next to the base, right? I've done that many times and nothing changes once I've picked up the controllers again. The hands are still in the air and screwed up.

**Comment by AlexLogin0ff** [comment]
"height" in the game!

**Comment by frictionjones** [comment]
Right, and once you press the right trigger to calibrate that height, the left controller floats in the air and is uncontrollable.

**Comment by hideinlight** [comment]
Trials of Tatooine not working for me.
Brookhaven demo doesn't work also.

**Comment by AlexLogin0ff** [comment]
For some games if not detected razer hydra are you need to run the game in Windows 7 compatibility mode just find the. Exe through steam and right click it and run the troubleshooter and you should be able to run it in Windows 7.

**Comment by hideinlight** [comment]
The windows 7 compatibility thing does work for me, I'm on Windows 10.
You see the the remotes in SteamVr, but as soon as the game launches they are gone and you can't even press start.

The green instruction screen also doesn't pop up.

**Comment by AlexLogin0ff** [comment]
example
![tg9fdtrzoqc](https://cloud.githubusercontent.com/assets/20149776/17142218/61b79bc8-5360-11e6-8846-ee845628e9ee.jpg)
