### ISSUE TITLE
Hands are swapped

### ISSUE THREAD

**Issue by tgraupmann** [betavr/steamvr_driver_hydra#28]
Is there a SteamVR configuration to swap controller hands?

Some games have the left hand in the right hand and vice-versa. If I swap hands, it's too smart and switches to be backwards again.

`steamvr.vrsettings`

```
{
   "dashboard" : {
      "enableDashboard" : false
   },
   "driver_osvr" : {
      "scanoutOrigin" : "lower-right",
      "verbose" : true
   },
   "steamvr" : {
      "mirrorViewGeometry" : "0 0 1080 600"
   }
}
```

**Comment by betavr** [comment]
Not really. Have you tried turning the base station around 180 degrees?
