### ISSUE TITLE
Controllers work in game, not in the Steam System UI

### ISSUE THREAD

**Issue by sebkajeka** [betavr/steamvr_driver_hydra#31]
I'm sure this used to work 4-5 months ago when I tested it. I can see and use the controllers in Steam Home but not in the Steam VR system menu. I don't have any laser pointers to interact with menus

**Comment by betavr** [comment]
I noticed it too. Apparently SteamVR has been changed in many important ways in relation to the input system since the last release of this driver.

I'm trying to fix it, please be patient.

@JoeLudwig

**Comment by betavr** [comment]
News break. 

The upgrade to OpenVR 1.0.16 is finished, the driver has its own controller bindings profile now in SteamVR. The profile still needs some work, but I can already use the hydra on the dashboard - laserpointers and buttons work as expected finally. Once that's finished I'll push out an update on Steam, probably this week if nothing goes wrong.

**Comment by betavr** [comment]
A new build has been pushed out to the beta branch on Steam: https://steamcommunity.com/games/steamvr_hydra_driver/announcements/detail/1711818454449860967

**Comment by critchi** [comment]
Hi. Thank you very much for this.

About the new driver, released as beta on steam, I managed to configure the bidings for Steam Home, and it works perfectly.

**Comment by critchi** [comment]
Hi. Thank you very much for this.

About the new driver, released as beta on steam, I managed to configure the bindings for Steam Home, and it works perfectly. the hydras appear and behave as expected.
For other apps though, different behaviors.

Google Earth:
You can't see the controllers at all, bindings don't work. If i get out of driver beta, then it works

**Comment by critchi** [comment]
Hi. Thank you very much for this.

About the new driver, released as beta on steam, I managed to configure the bindings for Steam Home, and it works perfectly. the hydras appear and behave as expected.
For other apps though, different behaviors.

Google Earth:
driver beta: You can't see the controllers at all, bindings don't work. If i get out of driver beta, then it works as expected, with default bindings

The Lab:
Beta: At first the controllers didn't appear, and I wasn't managing to save the bindings. I finally managed to save the bindings, you have to attribute all available commands to some button to be able to save.
after that, the controllers appeared in app, the binding works, but the controllers appear upside down, making them hard to use. 
out of beta: controllers don't show up anymore. (they used to work in this app).

Other apps, like the spider man far from home vr, it doesnt work in any mode, beta, out of beta, with bindings, etc.

Please do share any news and thanks again for this. this is the only way I can experience vr today

**Comment by r57zone** [comment]
In games, it also seems to have broken, for example, in PavlovVR it stopped working. Valve again broke something on SteamVR, a disgusting standard, constantly broaken.

Maybe if make the device ID "vive_controller" and impersonate yourself as "vive_controller" instead of "razer_hydra", maybe there will be no problems?
Valve constantly breaks everything, it's some kind of horror, not a standard.

UPD: What is surprising that PavlovVR works in [my driver](https://github.com/TrueOpenVR/SteamVR-TrueOpenVR) is weird. The menu button in the dashboard also works.

UPD 2: It turns out need to use custom bindings, then buttons and tracking work. Perhaps by default binding has some incompatibility with the new input.

UPD 3: [Driver with fix](https://github.com/r57zone/steamvr_driver_hydra).

**Comment by r57zone** [comment]
![](https://user-images.githubusercontent.com/9499881/191368809-551f99ad-d161-4d4d-a7c9-6e767eaa3799.gif)
Added recognition of Hydra controllers as Index controllers, this gives a little more convenient control and better compatibility (for example, with RE VR mods).
The updated driver can be found [here](https://github.com/r57zone/Razer-Hydra-SteamVR-driver).

**Comment by nerblock** [comment]
Great job! Unfortunately my hydra is problematic so I can't try it. But I can put up a beta branch for this version on Steam if you need it.

**Comment by betavr** [comment]
Great job @r57zone! Unfortunately my hydra has problems so I can't try it. But I can put up a beta branch for this version on Steam if you need it.

**Comment by r57zone** [comment]
Thanks, that would be great
