### ISSUE TITLE
Razer Hydra not detected at all by SteamVR

### ISSUE THREAD

**Issue by cyberbalrog** [betavr/steamvr_driver_hydra#32]
Hi, I've been struggling for the past month to get my VR setup working since the latest SteamVR update.

I can't seem to get the Hydra working at all. I've opted in for the beta release of the driver.

I've tried several combinations of betas of SteamVR, none seem to detect the Hydra anymore.
For quite some time I've had luck with the openvremulator temporary branch but since the last update, I don't even get the controller icons on the SteamVR status window.

Today I tried deleting everything related to SteamVR and Razer Hydra but still no luck. Any suggestions? Thanks in advance!

**Comment by betavr** [comment]
You'll have to upload vrserver.txt from the Steam logs directory to pastebin, and post a link to it.

But not here - the issue tracker is for development only, individual user problems belong in the Steam troubleshooting forum here: https://steamcommunity.com/app/491380/discussions/0/

I'm closing this, please open a topic there!
