### ISSUE TITLE
 Feature request: Dead zones X and Y for two controllers

### ISSUE THREAD

**Issue by r57zone** [betavr/steamvr_driver_hydra#33]
Hello, changing in config the dead zones x and y for the two controllers will fix the problems with the sticks of some people.

For example, sometimes my right stick goes to the left to -0.8. It would be desirable to correct a problem only there where it is namely only at one axis of one stick.

Thanks for your driver.

**Comment by betavr** [comment]
Hey @r57zone! 

The deadzone setting is implemented as a fix for the centering problem of the joysticks, which is a hardware problem (the springs in them get weaker over time).

It looks to me like you are having a known software issue with the joystick, which is most likely a problem in the sixense sdk. You need to replug the hydra to make the joystick center correctly (or restart the computer if you want to make sure).
