### ISSUE TITLE
Error 103

### ISSUE THREAD

**Issue by tkapis** [betavr/steamvr_driver_hydra#8]
I can't get this to work, I always get this error in vrserver .txt.

Sun Apr 24 2016 22:11:49.551 - Unable to load driver hydra from C:\Program Files (x86)\SteamVR Hydra driver\hydra\bin\win32\driver_hydra.dll.
Sun Apr 24 2016 22:11:49.551 - Unable to load driver hydra because of error 103. Skipping.

**Comment by betavr** [comment]
Install the latest VC runtime: https://www.microsoft.com/en-us/download/details.aspx?id=48145

Does it work if you copy the hydra folder to your SteamVR\drivers folder?
