### ISSUE TITLE
Deadzones on sticks

### ISSUE THREAD

**Issue by sigboe** [betavr/steamvr_driver_hydra#9]
Deadzone for the thumbsticks is needed badly, seeing as if the sticks are in use the menu button is disabled. And the sticks on the Hydra are as bad as on the Xbox 360. 😞

**Comment by betavr** [comment]
I already increased the deadzones a little to help this, but I think I can make it configurable so everyone can tune it to their own hydra.

**Comment by betavr** [comment]
Fixed in v1.0.1.4:

https://github.com/betavr/steamvr_driver_hydra/releases/tag/v1.0.1.4
